name: attract
version: 0.2.8
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: An example from boarding.
homepage: https://github.com/dzenanr/boarding
documentation: http://goo.gl/kXlDOJ
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  boarding: any
  browser: any
dev_dependencies:
  unittest: '>=0.9.3 <1.0.0'
transformers:
- $dart2js:
    minify: true
    terse: true